### ISSUE TITLE
hand detection

### ISSUE THREAD

**Issue by ihpannu** [nenadmarkus/picojs#17]
Hey I have a question if I want to do hand detection using is it possible to do it?

**Comment by AviKKi** [comment]
@iharmanpannu  It is a general object detection algorithm you can use it to detect hand, you just have to change the cascade https://github.com/tehnokv/picojs/blob/65dacf6a6938aa24beed5363105e1c219705145e/examples/image.html#L20

**Comment by Gauravnarulain** [comment]
where is another cascade URL to detect the hand or other objects like another face?
